export interface KpiDefinition {
  code: string;
  category: string;
  name: string;
  unit: string;
  target: number | null;
  redThreshold: number | null;
  amberThreshold: number | null;
  frequency: 'monthly' | 'quarterly' | 'annual';
}

export const KPI_CATEGORIES = [
  'Safety Performance',
  'Inspection & Audit',
  'Training & Competency',
  'Environmental',
  'Permit to Work',
  'Emergency Response',
  'Health & Welfare',
  'Subcontractor Management',
  'Eltizam Critical Controls',
  'Manpower & Compliance',
] as const;

export type KpiCategory = typeof KPI_CATEGORIES[number];

export const KPI_DEFINITIONS: KpiDefinition[] = [
  // ─────────────────────────────────────────────
  // 1. Safety Performance (8 KPIs)
  // ─────────────────────────────────────────────
  {
    code: 'EHSS-001',
    category: 'Safety Performance',
    name: 'Total Recordable Incident Rate (TRIR)',
    unit: 'rate',
    target: 0.5,
    redThreshold: 1.0,
    amberThreshold: 0.5,
    frequency: 'monthly',
  },
  {
    code: 'EHSS-002',
    category: 'Safety Performance',
    name: 'Lost Time Injury Frequency Rate (LTIFR)',
    unit: 'rate',
    target: 0.2,
    redThreshold: 0.5,
    amberThreshold: 0.2,
    frequency: 'monthly',
  },
  {
    code: 'EHSS-003',
    category: 'Safety Performance',
    name: 'Fatalities',
    unit: 'count',
    target: 0,
    redThreshold: 0,
    amberThreshold: null,
    frequency: 'monthly',
  },
  {
    code: 'EHSS-004',
    category: 'Safety Performance',
    name: 'First Aid Cases',
    unit: 'count',
    target: 5,
    redThreshold: 10,
    amberThreshold: 5,
    frequency: 'monthly',
  },
  {
    code: 'EHSS-005',
    category: 'Safety Performance',
    name: 'Near Miss Reports',
    unit: 'count',
    target: 10,
    redThreshold: 3,
    amberThreshold: 10,
    frequency: 'monthly',
  },
  {
    code: 'EHSS-006',
    category: 'Safety Performance',
    name: 'Lost Work Days',
    unit: 'count',
    target: 0,
    redThreshold: 5,
    amberThreshold: 0,
    frequency: 'monthly',
  },
  {
    code: 'EHSS-007',
    category: 'Safety Performance',
    name: 'Restricted Work Cases',
    unit: 'count',
    target: 0,
    redThreshold: 3,
    amberThreshold: 0,
    frequency: 'monthly',
  },
  {
    code: 'EHSS-008',
    category: 'Safety Performance',
    name: 'Safety Observation Rate',
    unit: 'rate per 100 workers',
    target: 20,
    redThreshold: 5,
    amberThreshold: 20,
    frequency: 'monthly',
  },

  // ─────────────────────────────────────────────
  // 2. Inspection & Audit (8 KPIs)
  // ─────────────────────────────────────────────
  {
    code: 'EHSS-009',
    category: 'Inspection & Audit',
    name: 'HSE Inspections Completed',
    unit: 'count',
    target: 20,
    redThreshold: 10,
    amberThreshold: 20,
    frequency: 'monthly',
  },
  {
    code: 'EHSS-010',
    category: 'Inspection & Audit',
    name: 'Inspection Findings Closed',
    unit: '%',
    target: 90,
    redThreshold: 70,
    amberThreshold: 90,
    frequency: 'monthly',
  },
  {
    code: 'EHSS-011',
    category: 'Inspection & Audit',
    name: 'NCR Closure Rate',
    unit: '%',
    target: 95,
    redThreshold: 80,
    amberThreshold: 95,
    frequency: 'monthly',
  },
  {
    code: 'EHSS-012',
    category: 'Inspection & Audit',
    name: 'Management Safety Tours',
    unit: 'count',
    target: 4,
    redThreshold: 2,
    amberThreshold: 4,
    frequency: 'monthly',
  },
  {
    code: 'EHSS-013',
    category: 'Inspection & Audit',
    name: 'Third Party Audit Score',
    unit: '%',
    target: 90,
    redThreshold: 70,
    amberThreshold: 90,
    frequency: 'quarterly',
  },
  {
    code: 'EHSS-014',
    category: 'Inspection & Audit',
    name: 'Internal Audit Findings Open',
    unit: 'count',
    target: 0,
    redThreshold: 10,
    amberThreshold: 0,
    frequency: 'monthly',
  },
  {
    code: 'EHSS-015',
    category: 'Inspection & Audit',
    name: 'Corrective Actions Overdue',
    unit: 'count',
    target: 0,
    redThreshold: 5,
    amberThreshold: 0,
    frequency: 'monthly',
  },
  {
    code: 'EHSS-016',
    category: 'Inspection & Audit',
    name: 'Compliance Audit Score',
    unit: '%',
    target: 95,
    redThreshold: 80,
    amberThreshold: 95,
    frequency: 'quarterly',
  },

  // ─────────────────────────────────────────────
  // 3. Training & Competency (8 KPIs)
  // ─────────────────────────────────────────────
  {
    code: 'EHSS-017',
    category: 'Training & Competency',
    name: 'Induction Completion Rate',
    unit: '%',
    target: 100,
    redThreshold: 90,
    amberThreshold: 100,
    frequency: 'monthly',
  },
  {
    code: 'EHSS-018',
    category: 'Training & Competency',
    name: 'Toolbox Talk Attendance',
    unit: '%',
    target: 95,
    redThreshold: 80,
    amberThreshold: 95,
    frequency: 'monthly',
  },
  {
    code: 'EHSS-019',
    category: 'Training & Competency',
    name: 'Competency Assessments Completed',
    unit: '%',
    target: 100,
    redThreshold: 85,
    amberThreshold: 100,
    frequency: 'quarterly',
  },
  {
    code: 'EHSS-020',
    category: 'Training & Competency',
    name: 'Specialized Training Completion',
    unit: '%',
    target: 100,
    redThreshold: 90,
    amberThreshold: 100,
    frequency: 'quarterly',
  },
  {
    code: 'EHSS-021',
    category: 'Training & Competency',
    name: 'Training Hours per Worker',
    unit: 'hours',
    target: 8,
    redThreshold: 4,
    amberThreshold: 8,
    frequency: 'monthly',
  },
  {
    code: 'EHSS-022',
    category: 'Training & Competency',
    name: 'Expired Certifications',
    unit: 'count',
    target: 0,
    redThreshold: 5,
    amberThreshold: 0,
    frequency: 'monthly',
  },
  {
    code: 'EHSS-023',
    category: 'Training & Competency',
    name: 'Emergency Drill Participation',
    unit: '%',
    target: 95,
    redThreshold: 80,
    amberThreshold: 95,
    frequency: 'quarterly',
  },
  {
    code: 'EHSS-024',
    category: 'Training & Competency',
    name: 'Supervisor HSE Training',
    unit: '%',
    target: 100,
    redThreshold: 90,
    amberThreshold: 100,
    frequency: 'quarterly',
  },

  // ─────────────────────────────────────────────
  // 4. Environmental (8 KPIs)
  // ─────────────────────────────────────────────
  {
    code: 'EHSS-025',
    category: 'Environmental',
    name: 'Environmental Incidents',
    unit: 'count',
    target: 0,
    redThreshold: 3,
    amberThreshold: 0,
    frequency: 'monthly',
  },
  {
    code: 'EHSS-026',
    category: 'Environmental',
    name: 'Waste Recycling Rate',
    unit: '%',
    target: 60,
    redThreshold: 30,
    amberThreshold: 60,
    frequency: 'monthly',
  },
  {
    code: 'EHSS-027',
    category: 'Environmental',
    name: 'Water Usage vs Target',
    unit: '%',
    target: 100,
    redThreshold: 80,
    amberThreshold: 100,
    frequency: 'monthly',
  },
  {
    code: 'EHSS-028',
    category: 'Environmental',
    name: 'Dust Complaints',
    unit: 'count',
    target: 0,
    redThreshold: 5,
    amberThreshold: 0,
    frequency: 'monthly',
  },
  {
    code: 'EHSS-029',
    category: 'Environmental',
    name: 'Noise Complaints',
    unit: 'count',
    target: 0,
    redThreshold: 3,
    amberThreshold: 0,
    frequency: 'monthly',
  },
  {
    code: 'EHSS-030',
    category: 'Environmental',
    name: 'Spill Incidents',
    unit: 'count',
    target: 0,
    redThreshold: 2,
    amberThreshold: 0,
    frequency: 'monthly',
  },
  {
    code: 'EHSS-031',
    category: 'Environmental',
    name: 'Carbon Emission Tracking',
    unit: '%',
    target: 100,
    redThreshold: 70,
    amberThreshold: 100,
    frequency: 'monthly',
  },
  {
    code: 'EHSS-032',
    category: 'Environmental',
    name: 'Environmental Compliance Score',
    unit: '%',
    target: 95,
    redThreshold: 80,
    amberThreshold: 95,
    frequency: 'quarterly',
  },

  // ─────────────────────────────────────────────
  // 5. Permit to Work (7 KPIs)
  // ─────────────────────────────────────────────
  {
    code: 'EHSS-033',
    category: 'Permit to Work',
    name: 'PTW Compliance Rate',
    unit: '%',
    target: 100,
    redThreshold: 90,
    amberThreshold: 100,
    frequency: 'monthly',
  },
  {
    code: 'EHSS-034',
    category: 'Permit to Work',
    name: 'PTW Audits Conducted',
    unit: 'count',
    target: 10,
    redThreshold: 5,
    amberThreshold: 10,
    frequency: 'monthly',
  },
  {
    code: 'EHSS-035',
    category: 'Permit to Work',
    name: 'PTW Violations',
    unit: 'count',
    target: 0,
    redThreshold: 3,
    amberThreshold: 0,
    frequency: 'monthly',
  },
  {
    code: 'EHSS-036',
    category: 'Permit to Work',
    name: 'Hot Work Permits Issued',
    unit: 'count',
    target: null,
    redThreshold: null,
    amberThreshold: null,
    frequency: 'monthly',
  },
  {
    code: 'EHSS-037',
    category: 'Permit to Work',
    name: 'Confined Space Entries',
    unit: 'count',
    target: null,
    redThreshold: null,
    amberThreshold: null,
    frequency: 'monthly',
  },
  {
    code: 'EHSS-038',
    category: 'Permit to Work',
    name: 'Excavation Permits',
    unit: 'count',
    target: null,
    redThreshold: null,
    amberThreshold: null,
    frequency: 'monthly',
  },
  {
    code: 'EHSS-039',
    category: 'Permit to Work',
    name: 'Working at Height Permits',
    unit: 'count',
    target: null,
    redThreshold: null,
    amberThreshold: null,
    frequency: 'monthly',
  },

  // ─────────────────────────────────────────────
  // 6. Emergency Response (7 KPIs)
  // ─────────────────────────────────────────────
  {
    code: 'EHSS-040',
    category: 'Emergency Response',
    name: 'Emergency Drills Conducted',
    unit: 'count',
    target: 2,
    redThreshold: 1,
    amberThreshold: 2,
    frequency: 'monthly',
  },
  {
    code: 'EHSS-041',
    category: 'Emergency Response',
    name: 'Emergency Response Time',
    unit: 'minutes',
    target: 5,
    redThreshold: 15,
    amberThreshold: 5,
    frequency: 'monthly',
  },
  {
    code: 'EHSS-042',
    category: 'Emergency Response',
    name: 'First Aider Ratio',
    unit: 'ratio per 50 workers',
    target: 1,
    redThreshold: 0.5,
    amberThreshold: 1,
    frequency: 'monthly',
  },
  {
    code: 'EHSS-043',
    category: 'Emergency Response',
    name: 'Fire Extinguisher Inspection',
    unit: '%',
    target: 100,
    redThreshold: 90,
    amberThreshold: 100,
    frequency: 'monthly',
  },
  {
    code: 'EHSS-044',
    category: 'Emergency Response',
    name: 'Emergency Equipment Status',
    unit: '%',
    target: 100,
    redThreshold: 90,
    amberThreshold: 100,
    frequency: 'monthly',
  },
  {
    code: 'EHSS-045',
    category: 'Emergency Response',
    name: 'Evacuation Drill Time',
    unit: 'minutes',
    target: 10,
    redThreshold: 20,
    amberThreshold: 10,
    frequency: 'quarterly',
  },
  {
    code: 'EHSS-046',
    category: 'Emergency Response',
    name: 'Communication System Test',
    unit: '%',
    target: 100,
    redThreshold: 90,
    amberThreshold: 100,
    frequency: 'monthly',
  },

  // ─────────────────────────────────────────────
  // 7. Health & Welfare (7 KPIs)
  // ─────────────────────────────────────────────
  {
    code: 'EHSS-047',
    category: 'Health & Welfare',
    name: 'Heat Stress Incidents',
    unit: 'count',
    target: 0,
    redThreshold: 5,
    amberThreshold: 0,
    frequency: 'monthly',
  },
  {
    code: 'EHSS-048',
    category: 'Health & Welfare',
    name: 'Medical Screenings Completed',
    unit: '%',
    target: 100,
    redThreshold: 90,
    amberThreshold: 100,
    frequency: 'monthly',
  },
  {
    code: 'EHSS-049',
    category: 'Health & Welfare',
    name: 'Occupational Health Cases',
    unit: 'count',
    target: 0,
    redThreshold: 3,
    amberThreshold: 0,
    frequency: 'monthly',
  },
  {
    code: 'EHSS-050',
    category: 'Health & Welfare',
    name: 'Welfare Facility Compliance',
    unit: '%',
    target: 100,
    redThreshold: 85,
    amberThreshold: 100,
    frequency: 'monthly',
  },
  {
    code: 'EHSS-051',
    category: 'Health & Welfare',
    name: 'Drinking Water Quality Checks',
    unit: '%',
    target: 100,
    redThreshold: 90,
    amberThreshold: 100,
    frequency: 'monthly',
  },
  {
    code: 'EHSS-052',
    category: 'Health & Welfare',
    name: 'Rest Break Compliance',
    unit: '%',
    target: 100,
    redThreshold: 90,
    amberThreshold: 100,
    frequency: 'monthly',
  },
  {
    code: 'EHSS-053',
    category: 'Health & Welfare',
    name: 'Worker Satisfaction Score',
    unit: '%',
    target: 80,
    redThreshold: 60,
    amberThreshold: 80,
    frequency: 'quarterly',
  },

  // ─────────────────────────────────────────────
  // 8. Subcontractor Management (7 KPIs)
  // ─────────────────────────────────────────────
  {
    code: 'EHSS-054',
    category: 'Subcontractor Management',
    name: 'Subcontractor Pre-qualification',
    unit: '%',
    target: 100,
    redThreshold: 90,
    amberThreshold: 100,
    frequency: 'quarterly',
  },
  {
    code: 'EHSS-055',
    category: 'Subcontractor Management',
    name: 'Subcontractor Audit Score',
    unit: '%',
    target: 85,
    redThreshold: 70,
    amberThreshold: 85,
    frequency: 'quarterly',
  },
  {
    code: 'EHSS-056',
    category: 'Subcontractor Management',
    name: 'Subcontractor NCR Rate',
    unit: 'count per sub',
    target: 1,
    redThreshold: 3,
    amberThreshold: 1,
    frequency: 'monthly',
  },
  {
    code: 'EHSS-057',
    category: 'Subcontractor Management',
    name: 'Subcontractor Training Compliance',
    unit: '%',
    target: 95,
    redThreshold: 80,
    amberThreshold: 95,
    frequency: 'monthly',
  },
  {
    code: 'EHSS-058',
    category: 'Subcontractor Management',
    name: 'Subcontractor TRIR',
    unit: 'rate',
    target: 0.5,
    redThreshold: 1.0,
    amberThreshold: 0.5,
    frequency: 'monthly',
  },
  {
    code: 'EHSS-059',
    category: 'Subcontractor Management',
    name: 'Subcontractor PTW Compliance',
    unit: '%',
    target: 100,
    redThreshold: 90,
    amberThreshold: 100,
    frequency: 'monthly',
  },
  {
    code: 'EHSS-060',
    category: 'Subcontractor Management',
    name: 'Subcontractor Performance Reviews',
    unit: '%',
    target: 100,
    redThreshold: 80,
    amberThreshold: 100,
    frequency: 'quarterly',
  },

  // ─────────────────────────────────────────────
  // 9. Eltizam Critical Controls (6 KPIs)
  // ─────────────────────────────────────────────
  {
    code: 'EHSS-061',
    category: 'Eltizam Critical Controls',
    name: 'Working at Height Controls',
    unit: '%',
    target: 100,
    redThreshold: 90,
    amberThreshold: 100,
    frequency: 'monthly',
  },
  {
    code: 'EHSS-062',
    category: 'Eltizam Critical Controls',
    name: 'Lifting Operations Controls',
    unit: '%',
    target: 100,
    redThreshold: 90,
    amberThreshold: 100,
    frequency: 'monthly',
  },
  {
    code: 'EHSS-063',
    category: 'Eltizam Critical Controls',
    name: 'Electrical Safety Controls',
    unit: '%',
    target: 100,
    redThreshold: 90,
    amberThreshold: 100,
    frequency: 'monthly',
  },
  {
    code: 'EHSS-064',
    category: 'Eltizam Critical Controls',
    name: 'Excavation Controls',
    unit: '%',
    target: 100,
    redThreshold: 90,
    amberThreshold: 100,
    frequency: 'monthly',
  },
  {
    code: 'EHSS-065',
    category: 'Eltizam Critical Controls',
    name: 'Confined Space Controls',
    unit: '%',
    target: 100,
    redThreshold: 90,
    amberThreshold: 100,
    frequency: 'monthly',
  },
  {
    code: 'EHSS-066',
    category: 'Eltizam Critical Controls',
    name: 'Energy Isolation (LOTO)',
    unit: '%',
    target: 100,
    redThreshold: 90,
    amberThreshold: 100,
    frequency: 'monthly',
  },

  // ─────────────────────────────────────────────
  // 10. Manpower & Compliance (6 KPIs)
  // ─────────────────────────────────────────────
  {
    code: 'EHSS-067',
    category: 'Manpower & Compliance',
    name: 'Total Manhours Worked',
    unit: 'hours',
    target: null,
    redThreshold: null,
    amberThreshold: null,
    frequency: 'monthly',
  },
  {
    code: 'EHSS-068',
    category: 'Manpower & Compliance',
    name: 'Overtime Percentage',
    unit: '%',
    target: 10,
    redThreshold: 15,
    amberThreshold: 10,
    frequency: 'monthly',
  },
  {
    code: 'EHSS-069',
    category: 'Manpower & Compliance',
    name: 'Absenteeism Rate',
    unit: '%',
    target: 3,
    redThreshold: 5,
    amberThreshold: 3,
    frequency: 'monthly',
  },
  {
    code: 'EHSS-070',
    category: 'Manpower & Compliance',
    name: 'Saudization Compliance',
    unit: '%',
    target: null,
    redThreshold: null,
    amberThreshold: null,
    frequency: 'quarterly',
  },
  {
    code: 'EHSS-071',
    category: 'Manpower & Compliance',
    name: 'Working Hours Compliance',
    unit: '%',
    target: 100,
    redThreshold: 90,
    amberThreshold: 100,
    frequency: 'monthly',
  },
  {
    code: 'EHSS-072',
    category: 'Manpower & Compliance',
    name: 'Ramadan Work Hour Compliance',
    unit: '%',
    target: 100,
    redThreshold: 90,
    amberThreshold: 100,
    frequency: 'annual',
  },
];

// Utility: get KPIs by category
export function getKpisByCategory(category: KpiCategory): KpiDefinition[] {
  return KPI_DEFINITIONS.filter((kpi) => kpi.category === category);
}

// Utility: get a single KPI by code
export function getKpiByCode(code: string): KpiDefinition | undefined {
  return KPI_DEFINITIONS.find((kpi) => kpi.code === code);
}
